version: "3.8"

services:
  postgres:
    container_name: ${APP_NAME}-db
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    profiles:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: links
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/
    networks:
      - default

  app-localdb:
    container_name: ${APP_NAME}
    build: ./
    env_file:
      - .env
    environment:
      - STORAGE_TYPE=memdb
    networks:
      - default
    profiles:
      - localdb
    ports:
      - ${SERVER_HTTP_HOST_PORT}:8000
      - ${SERVER_GRPC_HOST_PORT}:9000

  app-postgres:
    container_name: ${APP_NAME}
    build: ./
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - STORAGE_TYPE=postgre
    networks:
      - default
    profiles:
      - postgres
    ports:
      - ${SERVER_HTTP_HOST_PORT}:8000
      - ${SERVER_GRPC_HOST_PORT}:9000


volumes:
  db-data: