version: "3.8"

services:
  postgres:
    container_name: ${APP_NAME}-db
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: links
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - net1

  app:
    container_name: ${APP_NAME}
    build: ./
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - net1
    ports:
      - ${SERVER_HTTP_HOST_PORT}:8000
      - ${SERVER_GRPC_HOST_PORT}:9000
volumes:
  db-data:

networks:
  net1: