// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: shortlinks.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShortLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetShortLinkRequest) Reset() {
	*x = GetShortLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortlinks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortLinkRequest) ProtoMessage() {}

func (x *GetShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortlinks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortLinkRequest.ProtoReflect.Descriptor instead.
func (*GetShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_shortlinks_proto_rawDescGZIP(), []int{0}
}

func (x *GetShortLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetShortLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetShortLinkResponse) Reset() {
	*x = GetShortLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortlinks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortLinkResponse) ProtoMessage() {}

func (x *GetShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortlinks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortLinkResponse.ProtoReflect.Descriptor instead.
func (*GetShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_shortlinks_proto_rawDescGZIP(), []int{1}
}

func (x *GetShortLinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetBaseLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetBaseLinkRequest) Reset() {
	*x = GetBaseLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortlinks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBaseLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaseLinkRequest) ProtoMessage() {}

func (x *GetBaseLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortlinks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaseLinkRequest.ProtoReflect.Descriptor instead.
func (*GetBaseLinkRequest) Descriptor() ([]byte, []int) {
	return file_shortlinks_proto_rawDescGZIP(), []int{2}
}

func (x *GetBaseLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetBaseLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetBaseLinkResponse) Reset() {
	*x = GetBaseLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shortlinks_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBaseLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaseLinkResponse) ProtoMessage() {}

func (x *GetBaseLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortlinks_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaseLinkResponse.ProtoReflect.Descriptor instead.
func (*GetBaseLinkResponse) Descriptor() ([]byte, []int) {
	return file_shortlinks_proto_rawDescGZIP(), []int{3}
}

func (x *GetBaseLinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_shortlinks_proto protoreflect.FileDescriptor

var file_shortlinks_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x22, 0x28, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x26, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x22, 0x27, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x32, 0x9e, 0x01,
	0x0a, 0x0d, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12,
	0x44, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x4c, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10,
	0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x2f, 0x2e, 0x2e, 0x2f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shortlinks_proto_rawDescOnce sync.Once
	file_shortlinks_proto_rawDescData = file_shortlinks_proto_rawDesc
)

func file_shortlinks_proto_rawDescGZIP() []byte {
	file_shortlinks_proto_rawDescOnce.Do(func() {
		file_shortlinks_proto_rawDescData = protoimpl.X.CompressGZIP(file_shortlinks_proto_rawDescData)
	})
	return file_shortlinks_proto_rawDescData
}

var file_shortlinks_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shortlinks_proto_goTypes = []interface{}{
	(*GetShortLinkRequest)(nil),  // 0: proto.GetShortLinkRequest
	(*GetShortLinkResponse)(nil), // 1: proto.GetShortLinkResponse
	(*GetBaseLinkRequest)(nil),   // 2: proto.GetBaseLinkRequest
	(*GetBaseLinkResponse)(nil),  // 3: proto.GetBaseLinkResponse
}
var file_shortlinks_proto_depIdxs = []int32{
	2, // 0: proto.LinkShortener.GetBaseLink:input_type -> proto.GetBaseLinkRequest
	0, // 1: proto.LinkShortener.GetShortLink:input_type -> proto.GetShortLinkRequest
	3, // 2: proto.LinkShortener.GetBaseLink:output_type -> proto.GetBaseLinkResponse
	1, // 3: proto.LinkShortener.GetShortLink:output_type -> proto.GetShortLinkResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shortlinks_proto_init() }
func file_shortlinks_proto_init() {
	if File_shortlinks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shortlinks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShortLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shortlinks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShortLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shortlinks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBaseLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shortlinks_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBaseLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shortlinks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortlinks_proto_goTypes,
		DependencyIndexes: file_shortlinks_proto_depIdxs,
		MessageInfos:      file_shortlinks_proto_msgTypes,
	}.Build()
	File_shortlinks_proto = out.File
	file_shortlinks_proto_rawDesc = nil
	file_shortlinks_proto_goTypes = nil
	file_shortlinks_proto_depIdxs = nil
}
